import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Banner from "@/components/Home/Banner/Banner";
import StudyProcessContainer from "@/components/Home/StudyProcess/StudyProcess";
import SchoolDistrictContainer from "@/components/Home/SchoolDistrict/SchoolDistrict";
import Article from "@/components/Home/Article/ArticleContainer";
import CourseList from "@/components/CourseCenter/Course/CourseList/CourseList";
import TeachersList from "@/components/Home/Teachers/Teachers";
import HelpCenter from "@/components/Home/HelpCenter/HelpCenter";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>航程科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.banner}>
          <Banner />
          {/* <img src="/imgs/banner.png" alt="航程科技" title="航程科技" /> */}
        </div>

        <StudyProcessContainer />
        <SchoolDistrictContainer />
        <Article />
        <CourseList />
        <TeachersList />
        <HelpCenter />
      </main>
    </>
  );
}
